/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by build-extension.js or build-extension.py
 * To change values, edit extension/.env or set BACKEND_URL environment variable
 * Then run: node build-extension.js  OR  python build-extension.py
 */

const EXTENSION_CONFIG = {
  BACKEND_URL: 'http://localhost:5000',
  ENV_MODE: 'development',
  API_ENDPOINTS: {
    LOG_VIOLATION: '/log',
    SESSION: '/session',
    DASHBOARD: '/dashboard'
  }
};

// Export for use in background.js and popup.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = EXTENSION_CONFIG;
}
