#!/usr/bin/env python3

"""
Extension Build Script (Python version)
Generates extension/config.js with backend URL from environment variables or .env file

Usage:
    python build-extension.py
    BACKEND_URL=http://example.com python build-extension.py
    python build-extension.js (if Node.js is available)
"""

import os
import json
import sys
import re
from pathlib import Path

def load_env_file(env_path):
    """Load environment variables from .env file"""
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8-sig') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    if '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
    return env_vars

def main():
    print("Building extension configuration...")
    
    # Paths
    project_root = Path(__file__).parent
    extension_dir = project_root / 'extension'
    env_path = extension_dir / '.env'
    config_output_path = extension_dir / 'config.js'
    manifest_path = extension_dir / 'manifest.json'
    manifest_template_path = extension_dir / 'manifest.template.json'
    background_js_path = extension_dir / 'background.js'
    
    # Default config
    config = {
        'BACKEND_URL': 'http://localhost:5000',
        'ENV_MODE': 'development'
    }
    
    # Load from .env file
    if env_path.exists():
        print(f"Loading from {env_path}")
        env_vars = load_env_file(env_path)
        config.update(env_vars)
    else:
        print(f"Warning: .env file not found at {env_path}, using defaults")
    
    # Override with environment variables (takes precedence)
    if 'BACKEND_URL' in os.environ:
        config['BACKEND_URL'] = os.environ['BACKEND_URL']
    if 'ENV_MODE' in os.environ:
        config['ENV_MODE'] = os.environ['ENV_MODE']
    
    # Validate backend URL
    if not config.get('BACKEND_URL'):
        print("Error: BACKEND_URL not configured")
        sys.exit(1)
    
    # Remove trailing slash if present
    config['BACKEND_URL'] = config['BACKEND_URL'].rstrip('/')
    
    print(f"Backend URL: {config['BACKEND_URL']}")
    print(f"Environment: {config['ENV_MODE']}")
    
    # Generate config.js
    config_content = f"""/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by build-extension.py
 * To change values, edit extension/.env or set BACKEND_URL environment variable
 */

const EXTENSION_CONFIG = {{
  BACKEND_URL: '{config['BACKEND_URL']}',
  ENV_MODE: '{config['ENV_MODE']}',
  API_ENDPOINTS: {{
    LOG_VIOLATION: '/log',
    SESSION: '/session',
    DASHBOARD: '/dashboard'
  }}
}};

// Export for use in background.js and popup.js
if (typeof module !== 'undefined' && module.exports) {{
  module.exports = EXTENSION_CONFIG;
}}
"""
    
    with open(config_output_path, 'w', encoding='utf-8') as f:
        f.write(config_content)
    print(f"Generated {config_output_path}")
    
    # Update background.js to inject the backend URL for service worker
    try:
        with open(background_js_path, 'r', encoding='utf-8-sig') as f:
            background_js = f.read()
        
        # Replace the getDefaultBackendUrl function to return the configured URL
        # Supports both one-line () => 'url' and multi-line () => { ... } formats
        new_get_default = f"const getDefaultBackendUrl = () => '{config['BACKEND_URL']}';"
        
        background_js = re.sub(
            r"const getDefaultBackendUrl = \(\) => (\{[\s\S]*?\}|'.*?');",
            new_get_default,
            background_js
        )
        
        with open(background_js_path, 'w', encoding='utf-8') as f:
            f.write(background_js)
        
        print(f"Updated {background_js_path} with configured backend URL")
    except Exception as e:
        print(f"Warning: Could not update background.js: {e}")
    
    # Update manifest.json with correct host permissions
    host_permissions = [
        'http://127.0.0.1/*',
        'http://localhost/*',
        config['BACKEND_URL'] + '/*'
    ]
    
    try:
        # Check if template exists, use it; otherwise read existing manifest
        if manifest_template_path.exists():
            with open(manifest_template_path, 'r', encoding='utf-8-sig') as f:
                manifest_content = json.load(f)
            print(f"Using manifest template: {manifest_template_path}")
        else:
            with open(manifest_path, 'r', encoding='utf-8-sig') as f:
                manifest_content = json.load(f)
            print(f"Reading existing manifest: {manifest_path}")
        
        # Update host permissions
        if 'host_permissions' in manifest_content:
            manifest_content['host_permissions'] = host_permissions
        
        # Write updated manifest
        with open(manifest_path, 'w', encoding='utf-8') as f:
            json.dump(manifest_content, f, indent=2)
        
        print(f"Updated {manifest_path}")
        print(f"   Host permissions: {', '.join(host_permissions)}")
    except Exception as e:
        print(f"Error updating manifest: {e}")
        sys.exit(1)
    
    print("\nExtension build complete!")
    print("\nNext steps:")
    print("1. Load the extension in Chrome: chrome://extensions/ > Load unpacked > select extension/")
    print(f"2. The extension will connect to: {config['BACKEND_URL']}")

if __name__ == '__main__':
    main()
